SMS use and code changes for WAM coupling.

diff --git a/run/qsubipe b/run/qsubipe
--- a/run/qsubipe
+++ b/run/qsubipe
@@ -93,6 +93,28 @@ runscript_zeus() {
   echo "echo 'ipe failed' && exit 23"
 }
 
+runscript_theia() {
+
+  # Produce a script to run IPE on theia.
+
+  echo "#!/bin/bash -x"
+  echo "#PBS -A $acct"
+  echo "#PBS -d $PWD"
+  echo "#PBS -j oe"
+  echo "#PBS -l procs=$taskreq"
+  echo "#PBS -l walltime=$IPETIME"
+  echo "#PBS -N $jobname"
+  echo "#PBS -o output.batch"
+  echo "#PBS -q $IPEQUEUE"
+  echo "#PBS -W umask=022"
+  echo "export $envvars"
+  echo "$($modcmd $machine $compiler)"
+  echo "module list"
+  test $parallelism == parallel && extra="mpirun -np $tasks "
+  echo "time $extra./$(basename $exe) >output 2>&1 && echo 'ipe finished' && exit 0"
+  echo "echo 'ipe failed' && exit 23"
+}
+
 setc() {
 
   # Set variable to value only if variable is currently undefined.
@@ -132,7 +154,7 @@ sms_sets=""
 # Set up some lists of valid options for error checking.
 
 compilers="cray intel lahey pgi"
-machines="trillian zeus"
+machines="trillian zeus yellowstone theia"
 parallelisms="parallel serial"
 
 # Set variables for command-line arguments.
@@ -230,6 +252,36 @@ case $machine in
     esac
     ;;
 
+  # theia stanza
+
+  "theia")
+    compiler_check "intel pgi" $compiler $machine
+    setc IPEDATA  /scratch3/NCEPDEV/swpc/noscrub/Naomi.Maruyama/ipe/IPEdata/data
+#    setc IPEDATA  /scratch3/NCEPDEV/swpc/noscrub/Naomi.Maruyama/ipe/runs/tmp20150730/trunk/run/1444997033_ipe_theia_intel_parallel_80
+    setc IPEQUEUE debug
+    setc IPETIME  00:30:00
+    setc IPEWIND  /scratch3/NCEPDEV/swpc/noscrub/Naomi.Maruyama/ipe/IPEdata/wind
+    acct=swpc
+    griddir=/scratch3/NCEPDEV/swpc/noscrub/Naomi.Maruyama/ipe/grid
+    queue_cmd=qsub
+    case $sw_grid in
+      0) gridfile=$IPEDATA/ipe_grid                                               ;;
+      1) gridfile=$griddir/apex/1/GIP_apex_coords_global_lowres_new20120705         ;;
+      2) gridfile=$griddir/apex/2/GIP_apex_coords_global_lowres_new_2dynamo20120709 ;;
+      3) gridfile=$griddir/tldp/GIP_apex_coords_global_lowres_new_tilt20120709    ;;
+      *) fail "$0: Grid ID '$sw_grid' unknown."                                   ;;
+    esac
+    case $compiler in
+      intel)
+        envvars="MPI_BUFS_PER_HOST=2048 MPI_BUFS_PER_PROC=256"
+        ;;
+      lahey)
+        envvars="MPI_BUFS_PER_HOST=1024 MPI_BUFS_PER_PROC=128"
+        ipe_sets+=" -s nmswitch:mpstop=2"
+        ;;
+    esac
+    ;;
+
 esac
 
 pre=ipe_${machine}_${compiler}_${parallelism}
@@ -282,4 +334,5 @@ chmod 755 runscript
 jobid=$($queue_cmd runscript || echo FAIL)
 test $jobid == FAIL && fail "$0: Failed to submit job."
 echo "The job $jobid has been submitted."
+qstat -a |grep Naomi
 exit 0
