Added the test suite. Also added a barrier before the exchange. 640p run is b4b with r265. Passed the test suite.

diff --git a/run/qsubipeZeus b/run/qsubipeZeus
--- a/run/qsubipeZeus
+++ b/run/qsubipeZeus
@@ -45,8 +45,16 @@ cp ../wei96.cofcnts            .
 cp ../stup_ut_rec              .
 cp ../qsubipeZeus              .
 cp ../load_balance_groups1     .
-#ln -s /scratch2/portfolios/BMC/acb/IPEdata/* .
-ln -s /scratch2/portfolios/BMC/acb/IPEdata/IPEdata/* .
+
+set DATADIR="/scratch2/portfolios/BMC/acb/IPEdata/IPEdata"
+
+# Allow the test suite to override the data-files location.
+
+if ( $?IPEDATA ) then
+  set DATADIR="$IPEDATA"
+endif
+  
+ln -s $DATADIR/* .
 
 # Make rundir a full path for runscript
 set rundir = $cwd
@@ -86,14 +94,26 @@ EOF
 
 chmod 755 ./runscript
 
-qsub -N $name \
-     -A gm \
-     -q batch \
-#    -l partition=sjet \
-#    -l partition=tgpu \
-#    -l nodes=1:ppn=2 \
-     -l procs=$run_tasks \
-     -l walltime=$queue_time \
-     ./runscript || echo "qsub failed" && exit 1
+set QUEUE="batch"
+
+# Allow the test suite to override the batch queue.
+
+if ( $?IPEQUEUE ) then
+  set QUEUE="$IPEQUEUE"
+endif
+
+set jobid=`qsub -N $name -A nim -q $QUEUE -l procs=$run_tasks -l walltime=$queue_time -j oe ./runscript`
+
+if ( $status != 0 ) then
+  echo "qsub failed"
+  exit 1
+endif
+
+if ( "$jobid" == "" ) then
+  echo "Failed to get job ID"
+  exit 1
+endif
+  
+echo "The job $jobid has been submitted."
 
 exit 0
diff --git a/run/qsubipeZeusCV b/run/qsubipeZeusCV
--- a/run/qsubipeZeusCV
+++ b/run/qsubipeZeusCV
@@ -1,5 +1,5 @@
-#This script is for a compare_var run
 #!/bin/csh
+#This script is for a compare_var run
 #
 set queue_time=03:00:00
 if ( $#argv == 0 ) then
@@ -44,7 +44,19 @@ cp ../wei96.cofcnts            .
 cp ../stup_ut_rec              .
 cp ../qsubipeZeus              .
 cp ../load_balance_groups1     .
-ln -s /scratch2/portfolios/BMC/acb/IPEdata/* .
+
+# Allow the test suite to override the location of data files via environment
+# variable IPEDATA. If present in the environment, IPEDATA will specify the
+# location of the test suite's canned data archive; otherwise, the default path
+# will be used.
+
+if ( $?IPEDATA ) then
+  set DATADIR="$IPEDATA"
+else
+  set DATADIR="/scratch2/portfolios/BMC/acb/IPEdata/IPEdata"
+endif
+  
+ln -s $DATADIR/* .
 
 # Make rundir a full path for runscript
 set rundir = $cwd
@@ -84,14 +96,26 @@ EOF
 
 chmod 755 ./runscript
 
-qsub -N $name \
-     -A nim \
-     -q batch \
-#    -l partition=sjet \
-#    -l partition=tgpu \
-#    -l nodes=1:ppn=2 \
-     -l procs=$run_tasks \
-     -l walltime=$queue_time \
-     ./runscript || echo "qsub failed" && exit 1
+set QUEUE="batch"
+
+# Allow the test suite to override the batch queue.
+
+if ( $?IPEQUEUE ) then
+  set QUEUE="$IPEQUEUE"
+endif
+
+set jobid=`qsub -N $name -A nim -q $QUEUE -l procs=$run_tasks -l walltime=$queue_time -j oe ./runscript`
+
+if ( $status != 0 ) then
+  echo "qsub failed"
+  exit 1
+endif
+
+if ( "$jobid" == "" ) then
+  echo "Failed to get job ID"
+  exit 1
+endif
+  
+echo "The job $jobid has been submitted."
 
 exit 0
